version: '3.1'
services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Порт, на котором будет доступно ваше приложение Spring
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/courses
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - ./uploads:/uploads # Если ваше приложение работает с директориями
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    container_name: db
    image: postgres:latest
    restart: always
    ports:
      - "5430:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_DB: courses
      POSTGRES_PASSWORD: root
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./uploads:/app/uploads
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - spring-app

networks:
  mynetwork:
    driver: bridge

volumes:
  uploads:
