server:
  address: 0.0.0.0
  port: 80
spring:
  devtools:
    livereload:
      enabled: 'false'
  application:
    name: courses
  datasource:
    url: jdbc:postgresql://localhost:5433/courses
    driverClassName: org.postgresql.Driver
    username: rozoomcool
    password: secret
  jpa:
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    web: DEBUG
upload:
  path: C:\Users\User\PycharmProjects\deepfakebot\courseback\src\main\resources\media
token:
  access: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A7532785553A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A7532785553A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
  refresh: voU5327yQlMwfinvv2iSk2O4D6F247DF6E8teYqAeFD72tQcNL51556tSQWE5lHHZLf92qF1C4EA590A2D3B5Kzjs84EA1B423jwJfG7pHaLc5C36DtXNEN1xJk6r6t635A7kM3A73o05mv1HgXNmQ5Kzjs84EA1B423jwJfG7pHaLc5C36DtXNEN1xJk6r6t635A7kM3A73o05mv1HgXNmQ