server:
  address: 0.0.0.0
  port: 80
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  devtools:
    livereload:
      enabled: 'false'
  application:
    name: courses
  datasource:
    url: jdbc:postgresql://localhost:5432/courses
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    web: DEBUG
upload:
  path: uploads
token:
  access: 3623ae4c27783afa9ef9f0d99e12f6fdc9f9167400548867bcfea85f9e5e0cf9
  refresh: 89fd9b35f6aca3fff1bafa4eb93ff8d0fb3e16abd381efaf1677f8fd16013e19ff4b1da734e1439a1c66ec71ed729aae0212879700c17af365e06d29f8c02bf8